name: ${PROJECT_NAME}

services:
  devbox:
    build: 
      context: ./devbox
      dockerfile: Dockerfile.${ARCH}
      args:
        - PROXY=${PROXY}
    image: devbox:${ARCH}
    container_name: ${PROJECT_NAME}-devbox
    restart: unless-stopped
    ulimits:
      core:
        soft: -1
        hard: -1
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    tty: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace:cached
      - projects:/root/workspace/
    environment:
      - TZ=Asia/Shanghai
      - all_proxy=${PROXY}
      - ASAN_OPTIONS=abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1
    command: bash
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"

  relbox:
    build:
      context: ./relbox
      dockerfile: Dockerfile.${ARCH}
    image: relbox:${ARCH}
    container_name: ${PROJECT_NAME}-relbox
    restart: unless-stopped
    tty: true
    volumes:
      - projects:/root/workspace/
    environment:
      - TZ=Asia/Shanghai

volumes:
  projects:
    external: true

    