name: ${PROJECT_NAME}

services:
  devbox:
    build: 
      context: ./ubuntu-22.04
      dockerfile: Dockerfile.${ARCH}
      args:
        - PROXY=${PROXY}
    image: devbox-ubuntu-22.04:${ARCH}
    container_name: ${PROJECT_NAME}-ubuntu-22.04
    restart: unless-stopped
    ulimits:
      core:
        soft: -1
        hard: -1
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    tty: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace:cached
      - projects:/root/workspace/
    environment:
      - TZ=Asia/Shanghai
      - all_proxy=${PROXY}
    command: bash
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  projects:
    external: true

    