services:
  devbox:
    build: 
      context: .
      dockerfile: Dockerfile.${ARCH}
      network: host
    image: home.teraai.cn/hzcheng/devbox:${ARCH}
    container_name: ${PROJECT_NAME}-devbox
    restart: unless-stopped
    ulimits:
      core:
        soft: -1
        hard: -1
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # for docker-in-docker
      - ${VSCODE_SERVER_SOURCE:-vscode-server}:/root/.vscode-server
      - .:/workspace:cached
      - ${PROJECT_DATA_SOURCE:-project-data}:/root/workspace/
    environment:
      - TZ=Asia/Shanghai
      - DOCKER_BUILDKIT=1
      - all_proxy=${PROXY}
      - ASAN_OPTIONS=abort_on_error=1:disable_coredump=0:unmap_shadow_on_exit=1
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
    command: bash
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  vscode-server:
    name: ${PROJECT_NAME}-vscode-server
  project-data:
    name: ${PROJECT_NAME}-project-data
