# Stage 1: Prepare the CMake build environment
FROM alpine:latest AS cmake-builder

RUN apk add --no-cache curl

RUN curl -L -o cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-Linux-x86_64.sh

# Stage 2: Build the subscribe application
FROM gcc:9.3.0

COPY --from=cmake-builder /cmake-linux.sh /tmp/

RUN sh /tmp/cmake-linux.sh -- --skip-license --prefix=/usr/local && \
    rm /tmp/cmake-linux.sh

ENTRYPOINT [ "bash" ]

CMD []